### ISSUE TITLE
[FEEDBACK] Option to remove splashes completely

### ISSUE THREAD

**Issue by anoomolu** [Darkhax-Minecraft/Splashy#7]
### Minecraft Version

1.16.5

### Mod Loader

Forge

### Feedback

Hiya! Not sure how feasible it would be to do, but a neat feature for Splashy would be the ability to remove splashes from showing up entirely on the main menu. I'm on 1.16.5, and noticed that when using the existing config options, only one splash shows (rather than none at all), being some YouTube link I haven't looked up:

![image](https://github.com/Darkhax-Minecraft/Splashy/assets/77850233/77b98dd7-fb2f-4ef3-b0eb-c0f1db1a6c75)

I appreciate that 1.16 is an older version so no worries, but maybe people on newer releases might benefit from the added configurability?

**Comment by Darkhax** [comment]
Hello, 

With how things currently work the game must always have a splash text to avoid crashing. That YouTube video is used as a fail-safe and only shows up when no splashes are loaded. When making this mod my only focus was adding new splashes so I did not consider the ability to disable the feature entirely. Disabling them should be pretty easy though and I will look into adding it.

**Comment by Darkhax** [comment]
This feature has been added in the 7.0.3 update for MC 1.16.5. Just set `displaySplashes` to false. I will be adding this feature to newer versions eventually. Please note that CurseForge is currently having some issues with file review so it may take a few days for the file to show up. You can download the file directly from our maven for now using [this link](https://maven.blamejared.com/net/darkhax/splashy/Splashy-1.16.5/7.0.3/Splashy-1.16.5-7.0.3.jar).

**Comment by anoomolu** [comment]
Thank you!!
