### ISSUE TITLE
[FEEDBACK] Compatibility with any config mod

### ISSUE THREAD

**Issue by mrcisdaduntman** [Darkhax-Minecraft/Splashy#8]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

I've been trying config the mod but opening the config file though the game files is confusing. Opting for any of the config mods for forge does not seem to work the config is disabled. I'd recommend this mod  https://www.curseforge.com/minecraft/mc-mods/config-menus-forge

**Comment by Darkhax** [comment]
Hello, the config file for this mod requires a full game restart and can not be modified while the game is running. This makes it partially incompatible with mods like the one you linked. I've updated the [docs site](https://docs.darkhax.net/1.20.1/splashy/) with a full guide on how to use our config file.
